apiVersion: v1
kind: Pod
metadata:
  name: nodejs-app
  labels:
    run: nodejs-app
spec:
  containers:
    - name: nodejs
      image: hellojs
      imagePullPolicy: IfNotPresent
      ports:
        - containerPort: 8080