apiVersion: v1
kind: Pod
metadata:
  name: nodejs-app1
  labels:
    run: nodejs-app
spec:
  containers:
    - name: nodejs1
      image: hellojs1
      imagePullPolicy: IfNotPresent
      ports:
        - containerPort: 8080