apiVersion: v1
kind: Pod
metadata:
  name: nodejs-app2
  labels:
    run: nodejs-app
spec:
  containers:
    - name: nodejs2
      image: hellojs2
      imagePullPolicy: IfNotPresent
      ports:
        - containerPort: 8080