apiVersion: apps/v1
kind: Deployment
metadata:
  name: nodejs-app
  labels:
    run: nodejs-app
spec:
  replicas: 3
  selector:
    matchLabels:
      run: nodejs-app
  template:
    metadata:
      labels:
        run: nodejs-app
    spec:
      containers:
      - name: nodejs
        image: hellojs:1.0.0
        imagePullPolicy: IfNotPresent
        ports:
          - containerPort: 8080