apiVersion: v1
kind: Pod
metadata:
  name: nodejs-app
  labels:
    run: nodejs-app
spec:
  containers:
    - name: nodejs
      image: hellojs
      imagePullPolicy: IfNotPresent
      resources:
        requests:
          memory: "64Mi"
          cpu: "250m"
        limits:
          memory: "128Mi"
          cpu: "500m"
      ports:
        - containerPort: 8080